
platform :ios, '8.0'

project 'AiyaEffectsDemo.xcodeproj'

target 'AiyaEffectsDemo' do
    
    pod 'Masonry'
    
    pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'

end
