/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.3--ijk0.8.0--20170518--001"
#endif /* AVUTIL_FFVERSION_H */
